terraform {
  required_providers {
    azurerm = { source = "hashicorp/azurerm" }
    tls     = { source = "hashicorp/tls" }
  }
}

provider "azurerm" {
  features {}
}

# 1. Resource Group
resource "azurerm_resource_group" "vm" {
  name     = "rg-vm-demo"
  location = "Central India"
}

# 2. Virtual Network
resource "azurerm_virtual_network" "vm" {
  name                = "vnet-vm-demo"
  location            = azurerm_resource_group.vm.location
  resource_group_name = azurerm_resource_group.vm.name
  address_space       = ["10.10.0.0/16"]
}

# 3. Subnet
resource "azurerm_subnet" "vm" {
  name                 = "snet-vm-demo"
  resource_group_name  = azurerm_resource_group.vm.name
  virtual_network_name = azurerm_virtual_network.vm.name
  address_prefixes     = ["10.10.1.0/24"]
}

# 4. Public IP -- Standard SKU, matching the Standard NIC/VM default on
# current azurerm (Basic SKU IPs can't attach to a Standard-SKU setup).
resource "azurerm_public_ip" "vm" {
  name                = "pip-vm-demo"
  resource_group_name = azurerm_resource_group.vm.name
  location            = azurerm_resource_group.vm.location
  allocation_method   = "Static"
  sku                 = "Standard"
}

# 5. Network Security Group -- SSH only, open to the internet for demo
# convenience. Narrow source_address_prefix to your own IP before leaving
# this running for more than a quick test.
resource "azurerm_network_security_group" "vm" {
  name                = "nsg-vm-demo"
  location            = azurerm_resource_group.vm.location
  resource_group_name = azurerm_resource_group.vm.name

  security_rule {
    name                       = "AllowSSH"
    priority                   = 1001
    direction                  = "Inbound"
    access                     = "Allow"
    protocol                   = "Tcp"
    source_port_range          = "*"
    destination_port_range     = "22"
    source_address_prefix      = "*"
    destination_address_prefix = "*"
  }
}

# 6. Network Interface + NSG association
resource "azurerm_network_interface" "vm" {
  name                = "nic-vm-demo"
  location            = azurerm_resource_group.vm.location
  resource_group_name = azurerm_resource_group.vm.name

  ip_configuration {
    name                          = "internal"
    subnet_id                     = azurerm_subnet.vm.id
    private_ip_address_allocation = "Dynamic"
    public_ip_address_id          = azurerm_public_ip.vm.id
  }
}

resource "azurerm_network_interface_security_group_association" "vm" {
  network_interface_id      = azurerm_network_interface.vm.id
  network_security_group_id = azurerm_network_security_group.vm.id
}

# 7. SSH keypair, generated by Terraform itself -- so `terraform apply`
# alone is enough to get a working VM, no pre-existing keypair required.
# The private key only ever lives in Terraform state and this run's output;
# it's never written to disk automatically (see the ssh_private_key output).
resource "tls_private_key" "vm" {
  algorithm = "RSA"
  rsa_bits  = 4096
}

# 8. The VM -- smallest burstable size (Standard_B1s, eligible for the
# Azure free-tier 750 hrs/month), Ubuntu 22.04 LTS.
resource "azurerm_linux_virtual_machine" "vm" {
  name                  = "vm-demo"
  resource_group_name   = azurerm_resource_group.vm.name
  location              = azurerm_resource_group.vm.location
  size                  = "Standard_B1s"
  admin_username        = "azureuser"
  network_interface_ids = [azurerm_network_interface.vm.id]

  admin_ssh_key {
    username   = "azureuser"
    public_key = tls_private_key.vm.public_key_openssh
  }

  os_disk {
    caching              = "ReadWrite"
    storage_account_type = "Standard_LRS"
  }

  source_image_reference {
    publisher = "Canonical"
    offer     = "0001-com-ubuntu-server-jammy"
    sku       = "22_04-lts-gen2"
    version   = "latest"
  }
}

output "public_ip_address" {
  value = azurerm_public_ip.vm.ip_address
}

# Save with: terraform output -raw ssh_private_key > vm_key.pem && chmod 600 vm_key.pem
# Then: ssh -i vm_key.pem azureuser@<public_ip_address>
output "ssh_private_key" {
  value     = tls_private_key.vm.private_key_pem
  sensitive = true
}
