{{- if .Values.demoApp.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-{{ .Values.demoApp.name }}
  labels:
    app: {{ .Values.demoApp.name }}
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.demoApp.name }}
      release: {{ .Release.Name }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.demoApp.serviceMonitor.interval }}
{{- end }}
