apiVersion: v1
kind: Pod
metadata:
  name: zone-preferred
  labels:
    demo: node-affinity
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 80
        preference:
          matchExpressions:
          - key: zone
            operator: In
            values:
            - us-east
  containers:
  - name: nginx
    image: nginx:alpine
