services:
  coordinator:
    image: citusdata/citus:latest
    container_name: citus-coordinator

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shard_lab

    ports:
      - "5432:5432"

    volumes:
      - coordinator_data:/var/lib/postgresql

  worker1:
    image: citusdata/citus:latest
    container_name: citus-worker1

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shard_lab
    
    ports:
      - "5433:5432"

    volumes:
      - worker1_data:/var/lib/postgresql

  worker2:
    image: citusdata/citus:latest
    container_name: citus-worker2

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shard_lab

    ports:
      - "5434:5432"

    volumes:
      - worker2_data:/var/lib/postgresql

volumes:
  coordinator_data:
  worker1_data:
  worker2_data: