"""The dataset registry — the single source of truth for what this model trains on.

Both the data-preparation CLI and docs/DATASETS.md derive from this list, so the code
and the documentation cannot drift apart. Same corpus as the sibling custom-gpt-153m
project.
"""

from dataclasses import dataclass, field


@dataclass(frozen=True)
class DatasetSource:
    hf_id: str                  # Hugging Face dataset repo id
    name: str                   # human-readable name
    gated: bool                 # requires accepting terms on the HF website + a token
    schema: str                 # which parser branch handles it (see prepare.py)
    summary: str
    license_note: str
    tags: tuple = field(default_factory=tuple)

    @property
    def slug(self) -> str:
        """Local directory name under data/raw/."""
        return self.hf_id.replace("/", "__").replace(":", "__")


DATASETS = (
    DatasetSource(
        hf_id="HuggingFaceH4/ultrachat_200k",
        name="UltraChat 200k",
        gated=False,
        schema="conversation",
        summary=(
            "~200k filtered multi-turn dialogues, synthetically generated by having two "
            "ChatGPT models converse. Broad everyday-assistant coverage; the bulk of the "
            "conversational volume in this corpus."
        ),
        license_note="MIT. Derived from OpenAI model outputs — check OpenAI terms for commercial use.",
        tags=("multi-turn", "synthetic", "instruction-following"),
    ),
    DatasetSource(
        hf_id="OpenAssistant/oasst1",
        name="OpenAssistant Conversations (OASST1)",
        gated=False,
        # Not "conversation" (list-of-dicts) — the real raw schema is a flat table of
        # individual messages forming reply trees (message_id/parent_id/rank), reconstructed
        # into linear conversations by prepare.py's load_oasst_conversations(), not the
        # generic extract_turns() dispatch every other source goes through.
        schema="oasst_tree",
        summary=(
            "~161k human-written messages in crowd-sourced assistant conversation trees, "
            "35 languages (English-only subset used here), with human quality ratings. "
            "Real human phrasing rather than model-generated text — a useful counterweight "
            "to the synthetic sets."
        ),
        license_note="Apache-2.0.",
        tags=("multi-turn", "human-written", "multilingual"),
    ),
    DatasetSource(
        hf_id="zidankhan/databricks-dolly-15k",
        name="Databricks Dolly 15k",
        gated=False,
        schema="instruction",
        summary=(
            "~15k instruction/response pairs written by Databricks employees across "
            "brainstorming, classification, QA, generation, summarization, and extraction. "
            "Single-turn and hand-written, so it is small but unusually clean."
        ),
        license_note="CC BY-SA 3.0.",
        tags=("single-turn", "human-written", "instruction-following"),
    ),
    DatasetSource(
        hf_id="HuggingFaceTB/smoltalk",
        name="SmolTalk",
        gated=False,
        schema="conversation",
        summary=(
            "Compact multi-domain chat mixture assembled for training the SmolLM2 models, "
            "spanning everyday dialogue, reasoning, rewriting, and summarization."
        ),
        license_note="Apache-2.0.",
        tags=("multi-turn", "mixture", "compact"),
    ),
    DatasetSource(
        hf_id="HuggingFaceH4/no_robots",
        name="No Robots",
        gated=False,
        schema="conversation",
        summary=(
            "~9.5k prompts entirely human-written and human-answered (no model in the "
            "loop anywhere, unlike UltraChat/SmolTalk's synthetic generation) across 10 "
            "categories — Generation, Open QA, Brainstorm, Chat, Rewrite, Summarize, "
            "Coding, Classify, Closed QA, Extract. Modeled on OpenAI's InstructGPT "
            "human-demonstration data. Small, but a genuine third source of real human "
            "phrasing alongside OASST1, in different categories than either."
        ),
        license_note="CC BY-NC 4.0 — non-commercial use only.",
        tags=("single-turn", "human-written", "instruction-following"),
    ),
    DatasetSource(
        hf_id="openai/gsm8k",
        name="GSM8K",
        gated=False,
        schema="instruction",
        summary=(
            "~7.5k grade-school math word problems with explicit step-by-step worked "
            "solutions (calculator-annotated arithmetic, e.g. '48/2=24'), ending in a "
            "final '#### <answer>' line. instruction-schema columns are literally "
            "'question'/'answer', so no new parsing code was needed. Added specifically "
            "because this project's own QA reports showed the model attempting zero "
            "real arithmetic on simple word problems — this is worked-example reasoning "
            "data targeted at exactly that gap, not general corpus growth."
        ),
        license_note="MIT.",
        tags=("single-turn", "human-written", "math-reasoning"),
    ),
    DatasetSource(
        hf_id="lmsys/lmsys-chat-1m",
        name="LMSYS-Chat-1M",
        gated=True,
        schema="conversation",
        summary=(
            "1M real-world conversations between anonymous users and 25 different LLMs, "
            "collected via Chatbot Arena. The only source here with genuine unfiltered "
            "user prompts — messy, typo-ridden, and much closer to real traffic than the "
            "curated sets above."
        ),
        license_note=(
            "LMSYS-Chat-1M Dataset License — gated. Accept the terms on the dataset page "
            "and authenticate with an HF token before downloading."
        ),
        tags=("multi-turn", "real-user", "gated", "unfiltered"),
    ),
)

PUBLIC_DATASETS = tuple(d for d in DATASETS if not d.gated)
GATED_DATASETS = tuple(d for d in DATASETS if d.gated)


def by_id(hf_id):
    for source in DATASETS:
        if source.hf_id == hf_id:
            return source
    raise KeyError(f"Unknown dataset id: {hf_id}")


def selected(include_gated=True):
    return DATASETS if include_gated else PUBLIC_DATASETS
