apiVersion: v1
kind: Namespace
metadata:
  name: webapp-operator-python-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: webapp-operator-python
  namespace: webapp-operator-python-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: webapp-operator-python
rules:
  - apiGroups: ["webapp.platformlab.dev"]
    resources: ["webapps", "webapps/status"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["services", "events"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: webapp-operator-python
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: webapp-operator-python
subjects:
  - kind: ServiceAccount
    name: webapp-operator-python
    namespace: webapp-operator-python-system
