//! The dataset registry — a manually-synced Rust mirror of
//! `custom-gpt-153m/src/gpt/data/sources.py`'s `DATASETS`. That Python file stays the
//! single source of truth for `docs/DATASETS.md` generation; this list exists so
//! `build-corpus` can download/parse the same sources without a Python dependency at
//! run time. Keep the two in sync by hand when a dataset is added, removed, or
//! reclassified — there is no shared source both sides derive from.

/// Which row-parsing branch a source's raw parquet schema needs — mirrors
/// `sources.py`'s `schema` field exactly (`"conversation"` / `"instruction"` /
/// `"oasst_tree"`), see `parquet_rows.rs` for what each branch actually does.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Schema {
    Conversation,
    Instruction,
    OasstTree,
}

#[derive(Debug, Clone, Copy)]
pub struct DatasetSource {
    pub hf_id: &'static str,
    pub name: &'static str,
    pub gated: bool,
    pub schema: Schema,
    pub summary: &'static str,
}

impl DatasetSource {
    /// Local directory name under `<data-dir>/raw/` — `hf_id` with `/` and `:`
    /// replaced by `__`, matching `sources.py`'s `DatasetSource.slug`.
    pub fn slug(&self) -> String {
        self.hf_id.replace(['/', ':'], "__")
    }
}

pub const DATASETS: &[DatasetSource] = &[
    DatasetSource {
        hf_id: "HuggingFaceH4/ultrachat_200k",
        name: "UltraChat 200k",
        gated: false,
        schema: Schema::Conversation,
        summary: "~200k filtered multi-turn dialogues, synthetically generated by having two ChatGPT models converse.",
    },
    DatasetSource {
        hf_id: "OpenAssistant/oasst1",
        name: "OpenAssistant Conversations (OASST1)",
        gated: false,
        schema: Schema::OasstTree,
        summary: "~161k human-written messages in crowd-sourced assistant conversation trees, English-only subset used here.",
    },
    DatasetSource {
        hf_id: "zidankhan/databricks-dolly-15k",
        name: "Databricks Dolly 15k",
        gated: false,
        schema: Schema::Instruction,
        summary: "~15k instruction/response pairs written by Databricks employees.",
    },
    DatasetSource {
        hf_id: "HuggingFaceTB/smoltalk",
        name: "SmolTalk",
        gated: false,
        schema: Schema::Conversation,
        summary: "Compact multi-domain chat mixture assembled for training the SmolLM2 models.",
    },
    DatasetSource {
        hf_id: "HuggingFaceH4/no_robots",
        name: "No Robots",
        gated: false,
        schema: Schema::Conversation,
        summary: "~9.5k prompts entirely human-written and human-answered, no model in the loop.",
    },
    DatasetSource {
        hf_id: "openai/gsm8k",
        name: "GSM8K",
        gated: false,
        schema: Schema::Instruction,
        summary: "~7.5k grade-school math word problems with step-by-step worked solutions.",
    },
    DatasetSource {
        hf_id: "lmsys/lmsys-chat-1m",
        name: "LMSYS-Chat-1M",
        gated: true,
        schema: Schema::Conversation,
        summary: "1M real-world conversations between anonymous users and 25 different LLMs, gated.",
    },
];

pub fn selected(include_gated: bool) -> Vec<DatasetSource> {
    DATASETS
        .iter()
        .copied()
        .filter(|d| include_gated || !d.gated)
        .collect()
}
